version: '3'

services:

  web:
    build: .
    image: web
    environment:
      - POD_NAME=web
    restart: on-failure
    command: gunicorn web.asgi:application -k uvicorn.workers.UvicornWorker -w 8 -b 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  celery_beat:
    image: web
    environment:
      - POD_NAME=celery-beat
    restart: always
    command: celery -A web beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    volumes:
      - .:/app
    depends_on:
      - celery_worker

  celery_worker:
    image: web
    environment:
      - POD_NAME=celery-worker
    restart: always
    volumes:
      - .:/app
    command: celery -A web worker -E
    depends_on:
      - web


volumes:
    data:
